-- TABLE FOR TESTING
CREATE TABLE `HD_AUDIT_DB`.`DEPARTMENT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NULL,
  `RESPONSIBILITY` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`));

-- TABLE FOR TESTING
CREATE TABLE `HD_AUDIT_DB`.`EMPLOYEE` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(30) NULL,
    `ADDRESS` VARCHAR(60) NULL,
    `EMAIL` VARCHAR(40) NULL,
    `DEPARTMENT_ID` INT NULL,
    PRIMARY KEY (`ID`));
