CREATE DATABASE `HD_AUDIT_DB`;

CREATE TABLE `HD_AUDIT_DB`.`AUDIT_ACTION` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ACTION` VARCHAR(30) NOT NULL,
  `ACTION_DATE` DATETIME NULL,
  `ACTION_BY` VARCHAR(30) NULL,
  `ENTITY_NAME` VARCHAR(60) NULL,
  `ITEM_ID` INT NULL,
  `PROPERTY_NAME` VARCHAR(60) NULL,
  `OLD_VALUE` VARCHAR(100) NULL,
  `NEW_VALUE` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`));
